#!/bin/bash
#SBATCH --job-name=gts_mawps_omp_after
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 3-0:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o gts_mawps_omp_after.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry

for sparsity in 0.2 0.36 0.488 0.590 0.672 0.738 0.791 0.8325 0.866 0.893
do
saved_dir=/home/sliu/project_space/pruning_cfails/Math/gts/mawps/omp_after/$sparsity

python -m src.main -mode train -gpu 0 -embedding roberta -emb_name roberta-base -embedding_size 768 -hidden_size 512 \
-depth 2 -lr 0.001 -emb_lr 8e-6 -batch_size 4 -epochs 50 -dataset cv_mawps -full_cv -run_name run_cv_mawps \
--fix --sparse_init one_shot_gm --sparsity $sparsity --sparse --output_dir $saved_dir \
--pretrained_dir /home/sliu/project_space/pruning_cfails/Math/gts/mawps/dense/

done