#!/bin/bash
#SBATCH --job-name=gts_svamp_snip_rigl_mawps-asdiv-a_svamp
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 3-00:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o gts_svamp_snip_rigl_mawps-asdiv-a_svamp.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry

for sparsity in 0.2 0.36 0.488 0.590 0.672 0.738 0.791 0.8325 0.866 0.893
do
saved_dir=/home/sliu/project_space/pruning_cfails/Math/gts/mawps-asdiv-a_svamp/snip_rigl/$sparsity

python -m src.main -mode train -gpu 0 -embedding roberta -emb_name roberta-base -embedding_size 768 -hidden_size 512 \
-depth 2 -lr 0.001 -emb_lr 8e-6 -batch_size 8 -epochs 50 -dataset mawps-asdiv-a_svamp -run_name rnn_mawps-asdiv-a_svamp \
--sparse_init snip --sparsity $sparsity --sparse --output_dir $saved_dir  -save_model -no-full_cv -results \
--prune magnitude --prune_rate 0.5 --growth gradient --update_frequency 1000 --redistribution none -save_model

done