#!/bin/bash
#SBATCH --job-name=transformer_seq2seq_svamp_full_dense
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-12:00:00
#SBATCH --cpus-per-task=18
#SBATCH -o transformer_seq2seq_svamp_full_dense.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate prune_cry

python -m src.main -mode train -gpu 0 -embedding roberta -emb_name roberta-base -d_ff 256 -d_model 768 -lr 0.0001 \
-emb_lr 5e-6 -heads 4 -batch_size 4 -epochs 100 -dataset cv_svamp_augmented -full_cv -run_name run_full_cv_cv_svamp_augmented